### ISSUE TITLE
exports.name convention

### ISSUE THREAD

**Issue by jrburke** [nolanlawson/rollup-comparison#2]
@nolanlawson: following from the twitter conversation: rollup works by targeting modules with multiple exports and removing the exports that are not used. It might also benefit from just targeting single file bundles, so it might be able to condense some of the normal module APIs to just be identifiers inside a closure.

The ES2015 format makes it nice for removing exports from a multi-export module since the ES2015 syntax requires all exports to be top level statements in the module (not buried in if/else blocks, cannot dynamically generate them). This ensures static analysis can safely remove them if they are not referenced by another module.

A similar thing can be done in CommonJS modules by using the convention of attaching the named exports to the `exports` object in a consistent way, then writing AST trimming rules that removes them if they are not referenced.

So, in ES2015, if doing:

``` javascript
export function alpha() {}
export function beta() {}
```

In CommonJS:

``` javascript
exports.alpha = function() {};
exports.beta = function() {};
```

What is likely missing is a tree shaking project like rollup that targets those code patterns in CommonJS to do the AST work. However, it is possible to do using the same underlying technique in rollup.

The ES2015 module format is nice because the exports are forced to be top level, where in the CommonJS pathway, it is more of a convention. But if wanting to expand later to trim unused class prototype methods, it would use a related style of convention matching.

But rollup looks like a great choice if:
- You are already authoring your source in ES2015 module syntax, are OK with needing a transpiler for the code to run even in tests.
- Are just generating a single file library that is used by others (so no need for module meta properties like .id or .url, and do not need dynamic module loading).

Particularly since the alternative to stripping exports.name type of things may not exist yet.

**Comment by nolanlawson** [comment]
Hm, this sounds like exactly the kind of pattern I was trying to suss out in my example, though. I tend to dislike having a big utils class like you describe:

``` js
exports.doSomething = function () { / * ... */ };
exports.doAnotherThing = function () { / * ... */ };
exports.doSomethingElse = function () { / * ... */ };
```

This is inherently un-modular - functions can reference each other, it's hard to make custom builds, stuff you don't need can get included, etc.

But if I modularize those by extracting them into `doSomething.js`, `doAnotherThing.js`, and `doSomethingElse.js`, then browserify and webpack penalize me by adding per-module cruft, whereas rollup doesn't. Seems there's no way to get around this without basically de-modularizing your code...

**Comment by Rich-Harris** [comment]
> A similar thing can be done in CommonJS modules by using the convention of attaching the named exports to the `exports` object in a consistent way, then writing AST trimming rules that removes them if they are not referenced

Indeed – I wondered about the feasibility of creating a CJS -> ES2015 converter that did exactly that (since the lack of ES2015-ready packages, particularly on npm, is the main barrier to adoption. Chickens and eggs). The trouble is that even if it works 90% of the time, for the other 10% it will fail in confusing, hard-to-debug ways. See e.g. https://github.com/lodash/lodash/blob/master/lodash.js for an example of how `exports` gets abused.

So the question is this: is there any point coming up with a tree-shaking solution for AMD and CommonJS that will fail badly in a lot of situations _when ES2015 modules already exist_? Personally I think the answer is clearly 'no' – we should be spending our energy on making ES2015 modules the de facto choice. Anything else is like deciding whether to buy a better Betamax player or a better VHS player, when we're in the age of Netflix :grinning: 

(My own solution for situations where I need to use CommonJS modules from npm is to generate a CommonJS bundle from Rollup, then hand that over to Browserify. Things like bundle splitting and dynamic loading get a lil' tricky, but for me it's definitely been worth the trade-off.)

**Comment by jrburke** [comment]
@nolanlawson right, the webpack/browserify output might be more verbose for the "export one thing" style due to the bundling style for the module APIs. If rollup is smaller in the "export one thing" case too, then it is likely condensing the import/export calls to just local identifiers. That would be possible to do for CommonJS modules too, but I am not aware of a tool that does it today (could be one, I just have not looked for it).

@Rich-Harris:

> So the question is this: is there any point coming up with a tree-shaking solution for AMD and CommonJS that will fail badly in a lot of situations when ES2015 modules already exist?

We talked a bit after this on twitter too, but just to follow up: what exists for ES2015 modules is just a static definition of modules (no dynamic loading), [missing a few things](http://jrburke.com/2015/02/13/how-to-know-when-es-modules-are-done/), cannot run natively in JS engines yet. I agree on making ES2015 the full future, but that is more about spec and standards work, which moves very slowly. What exists today is effectively a coffeescript-level of description for modules. Which is great, some progress, and you can do something useful with that.

The flip side on a tool that works with CommonJS code, it could work for dependencies that are likely not published in ES2015 form to npm, requires less of a full stack conversion. rollup is doing some neat things, just calling out that those optimizations are not in the sole domain of ES2015 modules.

For cases where the exports are not known, or it is unclear what a consuming module imports, those would just keep all their exports, no trimming. So not a reduction in file size, but the code would not break.

An ES2015 solution would have to do something similar for `import * as lib...` cases where, lib.name might be used in a few different ways (hard to detect what lib[varName]() values would be for example).

In the end, tree shaking works on matching code patterns. ES2015 modules make this a bit nicer on the module boundary level, but still requires pattern matching. Once the tree shaking moves into removing class prototype methods or properties on objects, similar approaches work for CommonJS style modules.

But it is great to have rollup for the ES2015 cases, I definitely see its usefulness.

Closing this as just a discussion issue, no code changes to do.
